# see : https://github.com/micropython/micropython/issues/15228

# Hello in many different scripts

print("Latin/Western European")
print("English: Hello World")
print("Dutch: Hallo Wereld")
print("French: Bonjour le monde")
print("German: Hallo Welt")
print("Spanish: Hola Mundo")
print("Portuguese: Olá Mundo")
print("Italian: Ciao Mondo")

print("")
print("Nordic/Icelandic")
print("Icelandic: Halló heimur")
print("Swedish: Hej Världen")
print("Danish: Hej Verden")
print("Norwegian: Hei Verden")
print("Finnish: Hei Maailma")

print("")
print("Central European")
print("Czech: Ahoj světe")
print("Slovak: Ahoj svet")
print("Polish: Cześć Świecie")
print("Latvian: Sveika Pasaule")
print("Slovenian: Živjo Svet")
print("Hungarian: Helló Világ")
print("Romanian: Salut Lume")

print("")
print("Cyrillic")
print("Ukrainian: Привіт Світ")
print("Bulgarian: Здравей Свят")
print("Serbian: Здраво Свете")
print("Russian: Привет мир")
print("Belarusian: Прывітанне Свет")
print("Kazakh: Сәлем Әлем")

print("")
print("Greek")
print("Greek: Γειά σου Κόσμε")

print("")
print("Right-to-Left (RTL) Scripts")
print("Arabic: مرحبا بالعالم")
print("Hebrew: שלום עולם")
print("Persian: سلام دنیا")
print("Urdu: ہیلو دنیا")

print("")
print("South Asian/Indic")
print("Hindi: नमस्ते दुनिया")
print("Tamil: வணக்கம் உலகம்")
print("Telugu: నమస్కారం ప్రపంచం")
print("Kannada: ನಮಸ್ಕಾರ ಪ್ರಪಂಚ")
print("Malayalam: നമസ്കാരം ലോകം")
print("Bengali: নমস্কার বিশ্ব")
print("Punjabi: ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨੀਆ")
print("Sinhala: හෙලෝ වර්ල්ඩ්")

print("")
print("Southeast Asian")
print("Thai: สวัสดีโลก")
print("Lao: ສະບາຍດີໂລກ")
print("Burmese: မင်္ဂလာပါကမ္ဘာ")
print("Khmer: ជំរាបសួរពិភពលោក")
print("Vietnamese: Xin chào Thế giới")

print("")
print("East Asian")
print("Japanese: こんにちは世界")
print("Japanese Katakana: コンニチハセカイ")
print("Korean: 안녕하세요 세계")
print("Chinese Simplified: 你好世界")
print("Chinese Traditional: 你好世界")

print("")
print("African")
print("Swahili: Jambo Dunia")
print("Zulu: Sawubona Mhlaba")
print("Amharic: ሰላም ዓለም")
print("Hausa: Sannu Duniya")

print("")
print("Celtic/Gaelic")
print("Irish: Dia dhuit a Dhomhain")
print("Scottish Gaelic: Halò a Shaoghail")
print("Breton: Demat d'an Bed")
print("Welsh: Helo Byd")

print("")
print("Pacific/Polynesian")
print("Hawaiian: Aloha Honua")
print("Māori: Kia ora te Ao")
print("Samoan: Talofa Lalolagi")

print("")
print("Ancient Scripts")
print("Runic: ᚺᚨᛚᛚᛟ ᚹᛟᚱᛚᛞ")
print("Coptic: ⲬⲀⲒⲢⲈ ⲔⲞⲤⲘⲞⲤ")
print("Georgian: გამარჯობა სამყარო")
print("Armenian: Բարdelays Աdelays")

print("")
print("Emoji/Symbols")
print("Emoji: 👋🌍")
print("Emoji Mix: 😀 Hello World 🎉")

